version: 1
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%d.%m.-%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: bedpipy.log
    when: midnight
    interval: 7
    backupCount: 3 
loggers:
  spx:
    level: INFO
    handlers: [console,file]
    propagate: no
root:
  level: INFO
  handlers: [console,file]